##
## EPITECH PROJECT, 2018
## asm
## File description:
## asm
##

MKFILE_32	=	Makefile_32

MKFILE_64	=	Makefile_64

RM	=	rm -f

all:
	$(MAKE) -f $(MKFILE_64)

clean:
	$(MAKE) -f $(MKFILE_64) clean

fclean:
	$(MAKE) -f $(MKFILE_64) fclean

re: fclean all

.PHONY:	all clean fclean re
